<a href="https://colab.research.google.com/github/neeraj-pola/insurance_premium/blob/main/Insurance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [90]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [91]:
dataset = pd.read_csv("insurance.csv")
x = dataset.iloc[:, 0:-2].values
y = dataset.iloc[:, -1].values
print(x)

[[19 'female' 27.9 0 'yes']
 [18 'male' 33.8 1 'no']
 [28 'male' 33.0 3 'no']
 ...
 [18 'female' 36.9 0 'no']
 [21 'female' 25.8 0 'no']
 [61 'female' 29.1 0 'yes']]


In [92]:
print(y)

[16884.92  1725.55  4449.46 ...  1629.83  2007.95 29141.36]


In [93]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:, 1] = le.fit_transform(x[:, 1])
x[:, 4] = le.fit_transform(x[:, 4])
# x[:, 5] = le.fit_transform(x[:, 5])
print(x)

[[19 0 27.9 0 1]
 [18 1 33.8 1 0]
 [28 1 33.0 3 0]
 ...
 [18 0 36.9 0 0]
 [21 0 25.8 0 0]
 [61 0 29.1 0 1]]


In [94]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=11)
print(x_train)

[[50 1 32.2 0 0]
 [24 0 27.6 0 0]
 [48 1 29.7 0 0]
 ...
 [46 1 25.7 3 0]
 [55 1 32.7 1 0]
 [37 1 29.8 0 0]]


In [95]:
print(x_test)

[[19 0 34.7 2 1]
 [34 0 27.7 0 0]
 [42 0 33.2 1 0]
 ...
 [19 0 40.5 0 0]
 [28 1 27.0 2 0]
 [51 1 33.3 3 0]]


In [96]:
print(y_train[:50])

[ 8835.26 18955.22  7789.64 14283.46  3935.18  3044.21  3987.93 12950.07
 11576.13 46718.16 13012.21  9778.35  9788.87  1635.73  8733.23  4992.38
 11840.78  4686.39 22144.03  3292.53  4518.83 35147.53 12925.89  5972.38
 11658.38  2201.1  10435.07  6600.21  4883.87  1163.46  1727.79  3171.61
 48885.14  8428.07 29186.48 18223.45  7986.48 24393.62  1628.47  7419.48
 12979.36 41676.08 19199.94  1728.9   2866.09 14590.63  4846.92  1769.53
 12928.79 42760.5 ]


In [97]:
print(y_test[:15])

[36397.58  4415.16  7639.42  8965.8   9563.03 11454.02  5012.47 12648.7
 13451.12 39871.7   2480.98 11856.41 25517.11  2155.68  5261.47]


In [98]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)
print(x_test)

[[-1.46063388 -1.00749074  0.70253214  0.63400242  2.01410123]
 [-0.34326981 -1.00749074 -0.49734978 -0.95396625 -0.49649937]
 [ 0.2526577  -1.00749074  0.44541459 -0.15998192 -0.49649937]
 ...
 [-1.46063388 -1.00749074  1.69672002 -0.95396625 -0.49649937]
 [-0.79021544  0.99256495 -0.61733797  0.63400242 -0.49649937]
 [ 0.92307614  0.99256495  0.46255576  1.42798675 -0.49649937]]


In [99]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train,y_train)

LinearRegression()

In [100]:
y_pred = regressor.predict(x_test)
print(y_pred[:15])
print(y_test[:15])

[29073.78881276  5904.99524914 10557.17541658  8644.00025038
 13235.57262224 11364.70556406  8493.12944877 16776.99034213
 12800.20366971 34026.48074856  7194.45759568 16563.96138535
 10845.2387711   2687.73328335  6175.71548456]
[36397.58  4415.16  7639.42  8965.8   9563.03 11454.02  5012.47 12648.7
 13451.12 39871.7   2480.98 11856.41 25517.11  2155.68  5261.47]


In [101]:
from sklearn.metrics import r2_score
score = r2_score(y_pred,y_test)
print(score)

0.7419847208264118
